mappings:
  MisdirectionAdmin: 'Symbiote\misdirection\MisdirectionAdmin'
  MisdirectionAdminTestingExtension: 'Symbiote\misdirection\MisdirectionAdminTestingExtension'
  MisdirectionFallbackExtension: 'Symbiote\misdirection\MisdirectionFallbackExtension'
  SiteTreeMisdirectionExtension: 'Symbiote\misdirection\SiteTreeMisdirectionExtension'
  MisdirectionTesting: 'Symbiote\misdirection\MisdirectionTesting'
  LinkMapping: 'Symbiote\misdirection\LinkMapping'
  MisdirectionRequestFilter: 'Symbiote\misdirection\MisdirectionRequestFilter'
  MisdirectionService: 'Symbiote\misdirection\MisdirectionService'
  MisdirectionFunctionalTests: 'Symbiote\misdirection\tests\MisdirectionFunctionalTests'
  MisdirectionUnitTests: 'Symbiote\misdirection\tests\MisdirectionUnitTests'
